FROM node:20-alpine

WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./

# Install app dependencies
RUN npm ci

# Generate prisma client, leave out if generating in `postinstall` script
RUN npx prisma generate

# Change CMD to use npx directly to ensure process exits after migration
CMD ["npx", "prisma", "migrate", "deploy"]
