version: '2.2'

services:
  matchbased-app:
    image: '216989093428.dkr.ecr.eu-central-2.amazonaws.com/matchbased-repository-${ENVIRONMENT}'
    container_name: matchbased-app
    restart: 'always'
    ports:
      - '3000:3000'
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-2
        awslogs-group: 'matchbased-app-logs-${ENVIRONMENT}'
        #awslogs-create-group: 'true'
    env_file:
      - '.env'
    environment:
      - VIRTUAL_HOST=$API_HOST #TODO: Inject the host from variables, after creating the matchbased hosted zone atm test it with the default domain from ec2
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=$API_HOST
      - VIRTUAL_PATH=/
    networks:
      - matchbased

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - matchbased-app
    networks:
      - matchbased

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - matchbased

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  matchbased:
    name: matchbased
    external: false
